version: '3'

services:
  app:
    container_name: greevil-web
    restart: always
    build: ./src
    volumes:
      - /static:/static
    ports:
      - "8000:8000"
    command: sh -c "./manage.py collectstatic --noinput; gunicorn -w 2 -b 0.0.0.0:8000 ec2django.wsgi;"

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - /static:/static
    ports:
      - "80:80"
    depends_on:
      - app